//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modest100 {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Icons {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Icons() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedResources.Icons", typeof(Icons).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap _2012_09_04_csmidi {
			get {
				object obj = ResourceManager.GetObject("2012-09-04 csmidi", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon {
			get {
				object obj = ResourceManager.GetObject("balloon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon__arrow {
			get {
				object obj = ResourceManager.GetObject("balloon--arrow", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon__exclamation {
			get {
				object obj = ResourceManager.GetObject("balloon--exclamation", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon__minus {
			get {
				object obj = ResourceManager.GetObject("balloon--minus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon__pencil {
			get {
				object obj = ResourceManager.GetObject("balloon--pencil", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon__plus {
			get {
				object obj = ResourceManager.GetObject("balloon--plus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon_ellipsis {
			get {
				object obj = ResourceManager.GetObject("balloon-ellipsis", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon_left {
			get {
				object obj = ResourceManager.GetObject("balloon-left", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon_quotation {
			get {
				object obj = ResourceManager.GetObject("balloon-quotation", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon_small {
			get {
				object obj = ResourceManager.GetObject("balloon-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon_small_left {
			get {
				object obj = ResourceManager.GetObject("balloon-small-left", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon_smiley {
			get {
				object obj = ResourceManager.GetObject("balloon-smiley", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon_sound {
			get {
				object obj = ResourceManager.GetObject("balloon-sound", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon_white {
			get {
				object obj = ResourceManager.GetObject("balloon-white", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloon_white_left {
			get {
				object obj = ResourceManager.GetObject("balloon-white-left", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloons {
			get {
				object obj = ResourceManager.GetObject("balloons", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloons_box {
			get {
				object obj = ResourceManager.GetObject("balloons-box", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap balloons_white {
			get {
				object obj = ResourceManager.GetObject("balloons-white", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap binocular {
			get {
				object obj = ResourceManager.GetObject("binocular", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap binocular__arrow {
			get {
				object obj = ResourceManager.GetObject("binocular--arrow", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap binocular__exclamation {
			get {
				object obj = ResourceManager.GetObject("binocular--exclamation", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap binocular__minus {
			get {
				object obj = ResourceManager.GetObject("binocular--minus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap binocular__pencil {
			get {
				object obj = ResourceManager.GetObject("binocular--pencil", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap binocular__plus {
			get {
				object obj = ResourceManager.GetObject("binocular--plus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap block {
			get {
				object obj = ResourceManager.GetObject("block", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap block__arrow {
			get {
				object obj = ResourceManager.GetObject("block--arrow", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap block__exclamation {
			get {
				object obj = ResourceManager.GetObject("block--exclamation", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap block__minus {
			get {
				object obj = ResourceManager.GetObject("block--minus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap block__pencil {
			get {
				object obj = ResourceManager.GetObject("block--pencil", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap block__plus {
			get {
				object obj = ResourceManager.GetObject("block--plus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap block_small {
			get {
				object obj = ResourceManager.GetObject("block-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap blue_document_binary {
			get {
				object obj = ResourceManager.GetObject("blue-document-binary", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap blue_document_block {
			get {
				object obj = ResourceManager.GetObject("blue-document-block", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap blue_document_code {
			get {
				object obj = ResourceManager.GetObject("blue-document-code", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap blue_document_number {
			get {
				object obj = ResourceManager.GetObject("blue-document-number", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap blue_document_shred {
			get {
				object obj = ResourceManager.GetObject("blue-document-shred", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap boxed_blue_arrow_down {
			get {
				object obj = ResourceManager.GetObject("boxed_blue_arrow_down", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap boxed_blue_arrow_up {
			get {
				object obj = ResourceManager.GetObject("boxed_blue_arrow_up", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap boxed_empty_white {
			get {
				object obj = ResourceManager.GetObject("boxed_empty_white", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap boxed_green_minus {
			get {
				object obj = ResourceManager.GetObject("boxed_green_minus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap boxed_green_plus {
			get {
				object obj = ResourceManager.GetObject("boxed_green_plus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap card {
			get {
				object obj = ResourceManager.GetObject("card", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap card__arrow {
			get {
				object obj = ResourceManager.GetObject("card--arrow", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap card__exclamation {
			get {
				object obj = ResourceManager.GetObject("card--exclamation", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap card__minus {
			get {
				object obj = ResourceManager.GetObject("card--minus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap card__pencil {
			get {
				object obj = ResourceManager.GetObject("card--pencil", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap card__plus {
			get {
				object obj = ResourceManager.GetObject("card--plus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap card_address {
			get {
				object obj = ResourceManager.GetObject("card-address", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap card_export {
			get {
				object obj = ResourceManager.GetObject("card-export", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap card_import {
			get {
				object obj = ResourceManager.GetObject("card-import", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap card_medium {
			get {
				object obj = ResourceManager.GetObject("card-medium", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap card_small {
			get {
				object obj = ResourceManager.GetObject("card-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cards {
			get {
				object obj = ResourceManager.GetObject("cards", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cards_address {
			get {
				object obj = ResourceManager.GetObject("cards-address", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cards_bind {
			get {
				object obj = ResourceManager.GetObject("cards-bind", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cards_bind_address {
			get {
				object obj = ResourceManager.GetObject("cards-bind-address", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cards_stack {
			get {
				object obj = ResourceManager.GetObject("cards-stack", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cassette {
			get {
				object obj = ResourceManager.GetObject("cassette", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cassette__arrow {
			get {
				object obj = ResourceManager.GetObject("cassette--arrow", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cassette__exclamation {
			get {
				object obj = ResourceManager.GetObject("cassette--exclamation", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cassette__minus {
			get {
				object obj = ResourceManager.GetObject("cassette--minus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cassette__pencil {
			get {
				object obj = ResourceManager.GetObject("cassette--pencil", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cassette__plus {
			get {
				object obj = ResourceManager.GetObject("cassette--plus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cassette_label {
			get {
				object obj = ResourceManager.GetObject("cassette-label", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap cassette_small {
			get {
				object obj = ResourceManager.GetObject("cassette-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap category {
			get {
				object obj = ResourceManager.GetObject("category", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap chevron {
			get {
				object obj = ResourceManager.GetObject("chevron", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap chevron_expand {
			get {
				object obj = ResourceManager.GetObject("chevron-expand", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap chevron_small {
			get {
				object obj = ResourceManager.GetObject("chevron-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap chevron_small_expand {
			get {
				object obj = ResourceManager.GetObject("chevron-small-expand", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control {
			get {
				object obj = ResourceManager.GetObject("control", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_000_small {
			get {
				object obj = ResourceManager.GetObject("control-000-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_090 {
			get {
				object obj = ResourceManager.GetObject("control-090", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_090_small {
			get {
				object obj = ResourceManager.GetObject("control-090-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_180 {
			get {
				object obj = ResourceManager.GetObject("control-180", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_180_small {
			get {
				object obj = ResourceManager.GetObject("control-180-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_270 {
			get {
				object obj = ResourceManager.GetObject("control-270", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_270_small {
			get {
				object obj = ResourceManager.GetObject("control-270-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_cursor {
			get {
				object obj = ResourceManager.GetObject("control-cursor", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_double {
			get {
				object obj = ResourceManager.GetObject("control-double", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_double_000_small {
			get {
				object obj = ResourceManager.GetObject("control-double-000-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_double_090 {
			get {
				object obj = ResourceManager.GetObject("control-double-090", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_double_090_small {
			get {
				object obj = ResourceManager.GetObject("control-double-090-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_double_180 {
			get {
				object obj = ResourceManager.GetObject("control-double-180", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_double_180_small {
			get {
				object obj = ResourceManager.GetObject("control-double-180-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_double_270 {
			get {
				object obj = ResourceManager.GetObject("control-double-270", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_double_270_small {
			get {
				object obj = ResourceManager.GetObject("control-double-270-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_eject {
			get {
				object obj = ResourceManager.GetObject("control-eject", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_eject_small {
			get {
				object obj = ResourceManager.GetObject("control-eject-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_pause {
			get {
				object obj = ResourceManager.GetObject("control-pause", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_pause_record {
			get {
				object obj = ResourceManager.GetObject("control-pause-record", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_pause_record_small {
			get {
				object obj = ResourceManager.GetObject("control-pause-record-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_pause_small {
			get {
				object obj = ResourceManager.GetObject("control-pause-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_power {
			get {
				object obj = ResourceManager.GetObject("control-power", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_power_1 {
			get {
				object obj = ResourceManager.GetObject("control-power_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_power_small {
			get {
				object obj = ResourceManager.GetObject("control-power-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_record {
			get {
				object obj = ResourceManager.GetObject("control-record", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_record_small {
			get {
				object obj = ResourceManager.GetObject("control-record-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_skip {
			get {
				object obj = ResourceManager.GetObject("control-skip", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_skip_000_small {
			get {
				object obj = ResourceManager.GetObject("control-skip-000-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_skip_090 {
			get {
				object obj = ResourceManager.GetObject("control-skip-090", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_skip_090_small {
			get {
				object obj = ResourceManager.GetObject("control-skip-090-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_skip_180 {
			get {
				object obj = ResourceManager.GetObject("control-skip-180", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_skip_180_small {
			get {
				object obj = ResourceManager.GetObject("control-skip-180-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_skip_270 {
			get {
				object obj = ResourceManager.GetObject("control-skip-270", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_skip_270_small {
			get {
				object obj = ResourceManager.GetObject("control-skip-270-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_stop {
			get {
				object obj = ResourceManager.GetObject("control-stop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_stop_000_small {
			get {
				object obj = ResourceManager.GetObject("control-stop-000-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_stop_090 {
			get {
				object obj = ResourceManager.GetObject("control-stop-090", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_stop_090_small {
			get {
				object obj = ResourceManager.GetObject("control-stop-090-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_stop_180 {
			get {
				object obj = ResourceManager.GetObject("control-stop-180", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_stop_180_small {
			get {
				object obj = ResourceManager.GetObject("control-stop-180-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_stop_270 {
			get {
				object obj = ResourceManager.GetObject("control-stop-270", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_stop_270_small {
			get {
				object obj = ResourceManager.GetObject("control-stop-270-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_stop_square {
			get {
				object obj = ResourceManager.GetObject("control-stop-square", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap control_stop_square_small {
			get {
				object obj = ResourceManager.GetObject("control-stop-square-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap counter {
			get {
				object obj = ResourceManager.GetObject("counter", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap counter_count {
			get {
				object obj = ResourceManager.GetObject("counter-count", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap counter_count_up {
			get {
				object obj = ResourceManager.GetObject("counter-count-up", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap counter_reset {
			get {
				object obj = ResourceManager.GetObject("counter-reset", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap counter_stop {
			get {
				object obj = ResourceManager.GetObject("counter-stop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap equalizer {
			get {
				object obj = ResourceManager.GetObject("equalizer", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap equalizer__arrow {
			get {
				object obj = ResourceManager.GetObject("equalizer--arrow", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap equalizer__exclamation {
			get {
				object obj = ResourceManager.GetObject("equalizer--exclamation", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap equalizer__minus {
			get {
				object obj = ResourceManager.GetObject("equalizer--minus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap equalizer__pencil {
			get {
				object obj = ResourceManager.GetObject("equalizer--pencil", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap equalizer__plus {
			get {
				object obj = ResourceManager.GetObject("equalizer--plus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap equalizer_flat {
			get {
				object obj = ResourceManager.GetObject("equalizer-flat", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap equalizer_high {
			get {
				object obj = ResourceManager.GetObject("equalizer-high", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap equalizer_low {
			get {
				object obj = ResourceManager.GetObject("equalizer-low", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap function {
			get {
				object obj = ResourceManager.GetObject("function", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap gender {
			get {
				object obj = ResourceManager.GetObject("gender", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap gender_female {
			get {
				object obj = ResourceManager.GetObject("gender-female", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap imidi {
			get {
				object obj = ResourceManager.GetObject("imidi", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap midi_in {
			get {
				object obj = ResourceManager.GetObject("midi_in", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap music {
			get {
				object obj = ResourceManager.GetObject("music", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap music__arrow {
			get {
				object obj = ResourceManager.GetObject("music--arrow", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap music__exclamation {
			get {
				object obj = ResourceManager.GetObject("music--exclamation", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap music__minus {
			get {
				object obj = ResourceManager.GetObject("music--minus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap music__pencil {
			get {
				object obj = ResourceManager.GetObject("music--pencil", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap music__plus {
			get {
				object obj = ResourceManager.GetObject("music--plus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap music_beam {
			get {
				object obj = ResourceManager.GetObject("music-beam", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap music_beam_16 {
			get {
				object obj = ResourceManager.GetObject("music-beam-16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap music_small {
			get {
				object obj = ResourceManager.GetObject("music-small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		/// </summary>
		public static System.Drawing.Icon speaker_tosort {
			get {
				object obj = ResourceManager.GetObject("speaker_tosort", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap vst {
			get {
				object obj = ResourceManager.GetObject("vst", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
